version: '3.6'

services:

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_CONFIG=production
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - DATABASE_PROD_URL=postgres://postgres:postgres@users-db:5432/users_prod
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/app/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres